### ISSUE TITLE
needs howto on how to add photo to background 

### ISSUE THREAD

**Issue by scottstensland** [MethodGrab/firefox-open-image-in-new-tab#3]
its not obvious how to use this add-on

on a new tab I see no way to define the image to appear on a new tab background

there is nothing relevant in  context menu

the settings widget on new tab just takes me to   `about:preferences#home`

firefox nightly  76.0a1 (2020-03-18) (64-bit)
ubuntu 20.04

**Comment by MethodGrab** [comment]
Firstly, thanks for reporting this as an issue rather than going straight to leaving a negative review!

I believe you may be misunderstanding the purpose of the extension.  
Its aim is to allow you to open images that are embedded in a website as standalone images in a separate tab.  
You will see the context menu entry if you right click on an image.

It sounds like what you actually want is something like my [Custom New Tab Page](https://addons.mozilla.org/en-US/firefox/addon/custom-new-tab-page/) extension which would allow you to set a URL as your new tab page (however please be aware that there are some caveats that limit how this extension works).

Apologies for any confusion, I will try and update the add-on description to make things clearer.
